# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ dev ]

defaults:
  run:
    working-directory: ./ShipperAPI
    
jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
      
    - run: cd ~/actions-runner/deploy/shipperApi/shipperApi/ShipperAPI
    - run: sudo docker container stop shipper-container || true
    - run: sudo docker container stop shipper-postgres || true
    - run: sudo docker container prune -f
    - run: sudo docker image rm shipper || true
    - run: sudo docker build -t shipper .
    - run: sudo docker run --name shipper-postgres -e POSTGRES_ROOT_PASSWORD=postgres -e POSTGRES_DATABASE=postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -d shipperpostgres:latest
    - run: sudo docker run -p 8080:8080 --name shipper-container --link shipper-postgres:postgres shipper | echo "success" 
 